### ISSUE TITLE
Claiming Kyanite after 1 hour doesn't give you and Kyanite

### ISSUE THREAD

**Issue by clapierre** [onikamigames/starshipgame#109]
After equipping 3 ships with all NFT's and waiting 1 hour clicking on Claim and signing the transaction, it says "success" but 0 kyanite is in the "Total Kyanite" and clicking on claim again and signing now gives a "Transaction Error - wait until next claim period 3600 seconds".

Multiple people have reported this issue in Discord server today in the support voice chat.

**Comment by onikamigames** [comment]
Duplicated: #125
