### ISSUE TITLE
I can't log in easily in the game itself

### ISSUE THREAD

**Issue by TheNikoleodeon** [onikamigames/starshipgame#116]
When I log into the game I log in correctly hit the sync up ad hit the log in and authorized it on anchor but still no game loading. Please fix this. And when I build my starship while im putting nfts on my 2nd starship the nfts can put in the starship the anchor prompt failed i dunno why.

![starshiptestnet](https://user-images.githubusercontent.com/96097933/145927901-062983ec-a379-47b6-b356-59bed5576111.png)

**Comment by onikamigames** [comment]
You only need Sync Up button the first time you access the game. It's used to create the game account. To log in the game, simply press the LOGIN button.

Does this comment solve your problem?

**Comment by TheNikoleodeon** [comment]
Yes thank you for your help
