### ISSUE TITLE
No kyanite, even after claiming and refreshing

### ISSUE THREAD

**Issue by rushapoil** [onikamigames/starshipgame#125]
Since we have to wait an hour between each claiming try, i've setup the game, logged in, setup my ships full nfts, clicked claim then refresh. still 0 kyanite.
Waited an hour, claimed refresh, still nothing.
Waited another hour, claimed refresh, still nothing.
Screenshots of the 3 ships fully equipped and the main screen
not complaining, just reporting ;)
Good luck Jouse !

![image](https://user-images.githubusercontent.com/19320416/145975039-1954c094-458e-4735-afe1-3a3d6df880f0.png)
![image](https://user-images.githubusercontent.com/19320416/145975103-66b8d81a-cc45-4014-8789-1f9f89c760b2.png)
![image](https://user-images.githubusercontent.com/19320416/145975159-d357c6ad-f0bd-480c-a187-c48d1f3e7922.png)
![image](https://user-images.githubusercontent.com/19320416/145975353-1fabfdd7-0a44-47f4-af18-8ae752596de8.png)
![image](https://user-images.githubusercontent.com/19320416/145975397-cb02df04-5ab2-474d-bbb6-f9b241680b0d.png)

**Comment by SoaG-git** [comment]
Same

**Comment by ragnarokjc** [comment]
Same issue here. I would post screenshots etc. but they would be exactly the same as OP.

**Comment by Flipzyde2006** [comment]
Same Issue for me as well. Didn't want to flood with similar tickets.

**Comment by exkrima** [comment]
Same Issue

**Comment by Haanhai** [comment]
same issue

**Comment by nagsve** [comment]
Same here, I'm using a MacBook Pro 16 MacOS Monterey V 12.0.1 Chip Apple M1 Max, maybe the problem is here like most of the other problems I'm dealing with.

**Comment by brandonjolley136** [comment]
same issue

**Comment by FYamauti** [comment]
same Issue.

**Comment by onikamigames** [comment]
Fixed!

Clould you test it again and close the issue?

Thanks!

**Comment by rushapoil** [comment]
> Fixed!
> 
> Clould you test it again and close the issue?
> 
> Thanks!

will do, as soon as it's confirmed
If any of you here got some screenshot top post to confirm before me, feel free to do so. Just not the 500 kyanite the dev sent us.

**Comment by rushapoil** [comment]
ok it's working on my side now, good job !
