### ISSUE TITLE
Cannot Collect and Return/Claim a Planet - Ships Stuck

### ISSUE THREAD

**Issue by g1rg1s** [onikamigames/starshipgame#127]
Team, 

2/3 ships in test net have arrived at planets and I am unable to collect kyanite/claim the planet and continue. I click Collect and Return, sign the transaction in Anchor wallet, and encounter the attached: 

"Transaction Error
assertion failure with message: Account not found" 

Account name: girgisiscool
Key Info: {"active_key": {"public": "EOS5esYcP26qL3msyEF1Rsh9dpSi82rdQSbWm5RuBun1W6WYKPXbz", "private": "5J1L1ZMps1rQ3f2XU5rXHnYJoTij1bnzXbSh6jtDeVnzBLKGAyX"}, "owner_key": {"public": "EOS5YJ4Qh96j9V77YMR5ZemGTrCHppfisbbN1ksz6NLRD5bZQBcqP", "private": "5HrMeqfPWHVqapeC4PscEwiicC7XnpSUrXxMGwPfcXkMKifrAaH"}}, "account": "girgisiscool"}

![image](https://user-images.githubusercontent.com/96119961/145994179-cb24b1e9-b973-4e09-a8aa-a51e8d8becdd.png)
![image](https://user-images.githubusercontent.com/96119961/145994263-9c2dafa2-48f3-4395-93f4-ecea8e202c1b.png)
![image](https://user-images.githubusercontent.com/96119961/145994393-07b58d6b-674f-48f5-b9c8-93a04fe5aa5f.png)

Thanks,
John

**Comment by onikamigames** [comment]
Could you test it again and close the issue if it's fixed?

Thanks!

**Comment by g1rg1s** [comment]
This is resolved now. 

Thanks!
