### ISSUE TITLE
Unable to return from Planet: Error - Account not found

### ISSUE THREAD

**Issue by clapierre** [onikamigames/starshipgame#132]
Once I arrived at a planet on the radar screen for this ship I get the 
"Collect and return" button
Clicking on this now and signing the transaction I receive an error msg.

Transaction Error
assertion failure with message: Account not found

Further Info which may help
When I started I had 477 Starship in my account and bought another 122 last night.  I started with one Uncommon (green) and to Common (gray) ships
Last Night: I bought some more starship but my account should still be under the $500 worth of STARSHIP (currently: 597 Starship @ 0.76 = $454)
However In my hangar I see a Blue (Rare) and two Green (Uncommon) ships. that should only happen if I have over $501 right?

Not sure if this is why it saying the Account not found?  I just sent this ship out like 2 hours ago well after I bought that additional starship without issue.

**Comment by clapierre** [comment]
Follow-up: After repeated multiple attempts over a 15 min span I finally was able to get a "Success" when clicking and signing "Collect and Return". No idea why.  I didn't do anything.
And the ships in the hanger are still 1 Rare & 2 Common which doesn't make sense to me.

**Comment by onikamigames** [comment]
Fixed ;-)

**Comment by clapierre** [comment]
Oh guess you fixed that :) thanks!
