### ISSUE TITLE
Metamask won't sync

### ISSUE THREAD

**Issue by halincorte** [onikamigames/starshipgame#136]
Meta mask won't synch, but I can log into the game.  My inventory shows up but there are no ships even though I have enough Starship tokens in my MM account.

**Comment by halincorte** [comment]
I got it working now.  Ty for your response

**Comment by Kripto-hub** [comment]
How did you fix this? Ive got the same problem

**Comment by Evelloncrypto** [comment]
Try this guys
https://www.youtube.com/watch?v=o-R7gcFUsoo&t=5s

**Comment by onikamigames** [comment]
Fixed!

**Comment by BecKeN1** [comment]
Hi I'm having the same problem

Meta Add:
0xD113AF5219215a3DbB1EC30521dc7089A3B62E44

Wax name:
walastik1111


![IMG20211217002054](https://user-images.githubusercontent.com/96254156/146410534-b1a5ddcc-b12d-4c2c-a9f1-d48ab444cbc4.jpg)
