### ISSUE TITLE
Ships not showing up.

### ISSUE THREAD

**Issue by paulgoso** [onikamigames/starshipgame#146]
Hi there,

My testnet account name is: paulgosotest
I have done the instruction in the yt video that Katie has sent in discord but still not showing up.
I have 30 bucks worth of ss token in my metamask wallet.
I see there are many others having the same issue, hope the team will get onto it. Thanks!

**Comment by onikamigames** [comment]
Fixed! Could you check your hangar a close this issue?

Thanks!

**Comment by paulgoso** [comment]
Thank you very much.
