### ISSUE TITLE
starships do not appear 

### ISSUE THREAD

**Issue by athinodorosk** [onikamigames/starshipgame#147]
My testnet account name is: "athinodorosk" and the public id is"EOS7d8ThQDWeuHFUDyCB3LLie3Q7dMH5dpbTw9srqwaJKH7xHiNgY" 
I have done the instruction in the yt video that Katie has sent in discord but still not showing up.
I refresh and try to log in from chrome and brave browser
I have 47starship tokens in my metamask wallet.
I see there are many others having the same issue, hope the team will get onto it. Thanks!

**Comment by onikamigames** [comment]
Fixed! Could you check your hangar a close this issue?

Thanks!

**Comment by athinodorosk** [comment]
thank you so much
