### ISSUE TITLE
My starship dosent show

### ISSUE THREAD

**Issue by emongdgreat** [onikamigames/starshipgame#150]
Ï just cant play the game. My starship failed to show even if my Metamask wallet has 88$ worth of token

![ss](https://user-images.githubusercontent.com/96169693/146145354-90b1c1f4-55e1-4558-af43-e15f12cac5a6.png)
![ss2](https://user-images.githubusercontent.com/96169693/146145365-58bfecb3-2107-48f0-9535-e4f7cefa8e89.png)

**Comment by onikamigames** [comment]
No enough information.
