### ISSUE TITLE
No starships in the hanger

### ISSUE THREAD

**Issue by AndyStarShip** [onikamigames/starshipgame#151]
I hold more than enough starship tokens but I have no starship sin my hanger. I have refreshed the browser twice, I am using Chrome browser. I have also tested this with Brave browser and the same issue occurs.

25    andygrimesrn    0.00000000000000000    ......4e5gnn2    0x838a71a117e4e6ff9718043519b922ec993feba9    75192.27343750000000000    [ 1089, 1090, 1091 ]    0
![Screenshot (47)](https://user-images.githubusercontent.com/94114206/146187650-54e441f7-2766-435d-99e3-e6fdb34cd56c.png)

**Comment by onikamigames** [comment]
Fixed! Could you check your hangar a close this issue?

Thanks!

**Comment by AndyStarShip** [comment]
Yes, I now have my starships. Thank you.
