### ISSUE TITLE
Ship rarity based on # of starship?

### ISSUE THREAD

**Issue by clapierre** [onikamigames/starshipgame#152]
It seems that the rarity of the starships in your hanger is based on the # of starship not the value of said tokens.

IE: when I started initially I had 460 Starship tokens worth ~ $350 at the time.
In my hangar I got 1 uncommon and 2 common ships which makes sense since I am in the $100 - $500 range according to the GDD.
Yesterday, I bought more starship, so my total starship now is 597.84 worth ~$430.  
However, in my hangar I have 1 rare and 2 uncommon ships.  

So to me it looks like since I now have over 500 tokens of starship I got the 1 rare/2 uncommom, but it should be tied to price should it not?

**Comment by onikamigames** [comment]
Sorry, this (dynamical rarity) is not a functionality implemented in the the tesnet. Starships rarity values are fixed and not finals, too. All game balance parameters are changing every day. In this phase, only game mechanics are been tested.
