### ISSUE TITLE
Ship Countdown Ends - No Planet Claim/No Kyanite Collect & Return

### ISSUE THREAD

**Issue by g1rg1s** [onikamigames/starshipgame#165]
This bug has been present even prior to the addition of planet conquering. I'll watch the ship countdown end after sending it to a nearby planet. The timer hangs at 0, nothing happens, and I am able to Select Mission again and send the ship back out empty-handed. I have also run into this where the timer hits zero, I toggle between a few different screens, and come back to be able to Select Mission and send the ship back out.

This would be tragic after the game launches, as you spend kyanite to get to the planet and are left with no opportunity to conqeur/claim it or collect the kyanite from it. 

Please look into this and let me know your thoughts.

Thanks!

**Comment by g1rg1s** [comment]
Currently have 2 stuck at 0. I'm afraid to do anything or move screens as I'll lose the kyanite/planet opportunity

![image](https://user-images.githubusercontent.com/96119961/146473938-b6475153-2ab0-483e-ac3e-372d5975efed.png)
![image](https://user-images.githubusercontent.com/96119961/146474013-e8cdbdf3-201c-4293-aa72-836b947f2950.png)

**Comment by cfirick** [comment]
I am having the same issue.

**Comment by g1rg1s** [comment]
This is now happening over and over and I'm running out of kyanite. Please fix this intermittent issue!

**Comment by g1rg1s** [comment]
Team, 

This has happened consistently on the last 10+ missions I've sent out. I'll return to the game long after the ship travel timer has finished only to find that when I hit Select Mission I have to send my ships back out. I'm nearly out of kyanite. Can this be addressed please?

**Comment by g1rg1s** [comment]
Testnet account name: girgisiscool
BSC Wallet Address: 0xc23F01295A4fA890E752847624124C691CAe51fb

**Comment by Evelloncrypto** [comment]
See also 

https://github.com/onikamigames/starshipgame/issues/183

**Comment by Evelloncrypto** [comment]
**Do not send your ships to planet ID 0**

It's a metallic planet in the top quadrant, first sector, first system. Just don't do it!

**Comment by g1rg1s** [comment]
Confirmed that was the issue and just collected from a different planet. Thank you!
