### ISSUE TITLE
Unable to connect to WAX testnet for WRITE actions

### ISSUE THREAD

**Issue by Evelloncrypto** [onikamigames/starshipgame#184]
***FIXED ON GREYMASS/ANCHOR WALLET END***

Began happening around 6:30 PM UTC. Multiple reports from users. Log-in (READ) is working, but options (WRITE) in mission control and potentially hangar are not loading.

WAX address: evellontest4
MM address: 0x44fbB8b967773E97192d2c56C17fF8447385A6fd
Chrome browser

https://user-images.githubusercontent.com/89880837/146652134-a2374973-7e95-458d-9dfb-26430b6c5fd6.mp4

**Comment by G00DW1LL** [comment]
Noticed when claiming and returning as well as sending off to missions.  Just stays on preparing request.

**Comment by Mustang12345** [comment]
Same

**Comment by grandpa12345** [comment]
greymass is currently not connecting to anchor wallet

**Comment by djcartledge** [comment]
same issue for me too - says not connecting

**Comment by mrtambo22** [comment]
Same issue
