### ISSUE TITLE
No starship in my hangar

### ISSUE THREAD

**Issue by Pwertz** [onikamigames/starshipgame#190]
Hi, why i have no starship in my hangar? I already connect my metamask wallet with starship token worth $10++. Please assist me on this. Thanks.

**Comment by DRAKENKUNGAMING** [comment]
Hi, I have the same problem where in my hangar doesn't show all the starship. What's worst is that my previous account where all the starship we're properly working is no longer available in anchor wallet. 

I have a youtube channel that's covering starship exclusively and so many people are waiting for this update. Thank you so much and more power!

**Comment by DRAKENKUNGAMING** [comment]
Here's my testnet account. "drakenkun123"
