### ISSUE TITLE
Cannot see ships in hangar

### ISSUE THREAD

**Issue by AlienScumCoinReaper** [onikamigames/starshipgame#195]
I cannot see my ships in my hanger and it says I am connected to my MetaMask wallet with 431 $starship tokens in it. Can you help?
ID- planetcaravn
BSC- 0x6071D71daBB01bF76E3Ba09Bc54716F652Ad7B9c
Google Chrome- Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by grandpa12345** [comment]
please add account name bsc address and browser version

**Comment by grandpa12345** [comment]
Wallet is linked to account name alienscumbag player had to make a new account which is above needs old sync removed so he can sync correct account
