### ISSUE TITLE
RARITY Inclusion when building starship

### ISSUE THREAD

**Issue by KateKate061992** [onikamigames/starshipgame#197]
Please include rarity in each card (must be visible) when building starship. Please note that not all players will be able do differentiate the rarity of each card only based on their colors. Some players wanted to build one starship with high end rarity of cards as components (legendary, mythic). Some others wanted it distributed (with common & high end parts)

![image](https://user-images.githubusercontent.com/82374510/146729758-235dacea-7365-45ad-8ee2-e2eaac40c696.png)

**Comment by NathTheDude** [comment]
perhaps employ a magnifying glass of sorts that when you hover over it or click it the card size will expand and also note rarity.
