### ISSUE TITLE
Staking of Kyanita

### ISSUE THREAD

**Issue by Pwertz** [onikamigames/starshipgame#201]
Hi, i would like to report a bug on my starship, coz it's been a day that i haven't recieve any kyanita even though i have a 3 starship and already equiped the parts that i've got in wax testnet. Thank you and hoping that you can resolve this as soonest.

**Comment by Evelloncrypto** [comment]
Click the claim button. Need to hit it every hour to get enough to start a mission

![image](https://user-images.githubusercontent.com/89880837/146873310-b1a61019-e9b6-44b6-b4f7-d7ecc2a023a4.png)

**Comment by Pwertz** [comment]
Hi it's me again, yes i already have kyanita on staked kyanita but when i
used to claim it, It didn't work to claim the kyanita, what should i do?
Thank you.
