### ISSUE TITLE
No starships in hanger

### ISSUE THREAD

**Issue by wonderfulbald** [onikamigames/starshipgame#204]
I believe I need my account reset that is associated with the game. I can't see the starships.

please connect 0x1250D82a3328431E26E9A311447707ad3Cf755ff to wax test account happybaldgyy.

Thanks

Network | 56
-- | --
Chain ID | 0x38
Accounts | 0x1250d82a3328431e26e9a311447707ad3cf755ff

**Comment by rytisguru** [comment]
Ya fix this finally guys!!! The F*uck are you doing? It's one week and you did nothing!!!

**Comment by wonderfulbald** [comment]
![image](https://user-images.githubusercontent.com/96489743/147175860-4eb5abb7-540e-491d-a7ad-6cc59790a964.png)

Please remove happybaldguy please. I lost the private keys and now trying to sync with happybaldgyy.
