### ISSUE TITLE
Cant Get past space station

### ISSUE THREAD

**Issue by Barabas0** [onikamigames/starshipgame#358]
Brave browser with shields down Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

0xf92B6EDD0d62e12f718A5a442D10981C1F6537cF
miuvy.wam

I have a second account that I was able to get to work on chrome,  tried the above account on chrome after brave failed and still could not get it to work.  Tried a bunch of suggested actions but were unsucessful.

**Comment by Onikamitest** [comment]
Ok, account removed, you can sync again and check. Confirm is it's okay.

**Comment by Barabas0** [comment]
> Ok, account removed, you can sync again and check. Confirm is it's okay.

I have tried multiple times even after re-sync,  only difference between my working account and this one is when I click on wax login it auto connects me to the space station page, I have turned off all auto login with wax but it does it anyway, it does ask for permission when I select a space station. On my working account it asks for permission on the wax login.
