### ISSUE TITLE
Purchased Planets Issue?

### ISSUE THREAD

**Issue by Double0Sebaz** [onikamigames/starshipgame#382]
I have purchased several planets for passive income on AtomicHub and I cannot see them in the game.  Do we need to somehow load them?  Also where do we see the 5% Kyanite we have received from those mining it?

Wax Wallet ek4iq.wam
MM: 0xFA706259c17E547d87CE2cA18Add218a139B95c3

**Comment by cmanshaw** [comment]
I am also having this issue. Purchased one Paradise Planet and it is not showing up on my planet panel 

Wax Wallet fzx.m.c.wam
