### ISSUE TITLE
Transaction Error when trying to move to planet

### ISSUE THREAD

**Issue by aleluja22** [onikamigames/starshipgame#40]
Transaction Error
assertion failure with message: Space Station stored in starship not found

**Comment by aleluja22** [comment]
![image](https://user-images.githubusercontent.com/95059009/143511953-fd66cc03-906a-471e-9e7f-ad73f34e4c5a.png)

**Comment by jmdystarship** [comment]
![image](https://user-images.githubusercontent.com/95058775/143513742-2217b18c-ebff-4d5b-9bef-504e7e19247c.png)

**Comment by pendulumocta** [comment]
same error i cant play =(
