### ISSUE TITLE
Cannot get past space station select screen

### ISSUE THREAD

**Issue by robbieillz** [onikamigames/starshipgame#427]
Hello - ive tried:

- Windows and Mac
- Firefox, Chrome and Brave
- There is no auto-approve on (i click approve at login screen and in space station connect)
-  i have 23 Starship in metamask (0x35faf55F4A2D86B0F21BfF7da29A5b9557A6D8AD)

![image](https://user-images.githubusercontent.com/69651966/147795238-7f262084-5a57-459c-a750-fc21242223d1.png)

- i have tried all the refreshing in the discord channels
Here is my wax staking (ayqr.wam)

![image](https://user-images.githubusercontent.com/69651966/147795266-02e2bc95-f6db-487e-a70e-887a31970c7b.png)

**Comment by robbieillz** [comment]
i have also tried for two days.

**Comment by macple01** [comment]
bulok tong game nato tang ina nila. pinili lang mga players nito ayang investment.!

**Comment by ashtag06** [comment]
Same plus I have 200 wax CPU etc

**Comment by robbieillz** [comment]
make that three days - tried again this morning on chrome - also im not spamming the chain - i try the login - spacestation select - refresh try again once.

**Comment by robbieillz** [comment]
ive submitted my wax wallet for unsync ayqr.wam

**Comment by robbieillz** [comment]
hello? when will wave 3 be unsynced?  i see no announcements in the discord about this.

**Comment by robbieillz** [comment]
unsync has fixed this closing - nice talking you all...
