### ISSUE TITLE
starship rarity not change

### ISSUE THREAD

**Issue by Aerogaming92** [onikamigames/starshipgame#482]
i already add starship token which is worth 100 usd to have rare starship but my ship still uncommon or not change at all i hope u can fix this one  like my other issue in the game earlier thank you for your response. 

metamsk: 0xa98269acDeD5235b6dDB1a647FF074504b1BCdDc
wax wallet: zd1xg.wam

**Comment by Locke333** [comment]
Same problem, this needs to be adjusted because we are putting money in those token to get better stats but nothing is changing. at least add a manual buton or modify the sync process to allow us to trigger the revalidation of the owned starship token if you cannot automate it at this point

**Comment by gitarnel2301** [comment]
Good Day, same issue with my account
wax wallet: w55z4.wam
metamask wallet : 0xA768aD82557DFDCc6D37B2E0338bC055f149AE47

**Comment by Jhenea** [comment]
Same issue

wax wallet: ljcig.wam
metamask wallet : 0xc2C6FdF88B863c950830162Ca20584abc23197FD
