### ISSUE TITLE
My ship downgraded again

### ISSUE THREAD

**Issue by jsbalasbas** [onikamigames/starshipgame#529]
Why does my ship downgrade again. 
 I have attached picture of my previous stats vs my new ship stats.

Please fix this. Thank you.

Wax ID: 3brza.wam

Metamask: 0xD8eE7Dc3f1bcc97036c14e4e7Bd0561Aa8d174F2

![PREVIOUS SHIP STATS](https://user-images.githubusercontent.com/96989475/148254578-1a83f6d7-b7b3-4736-bc30-ff2cf62d6f6c.JPG)
![NEW SHIP STATS](https://user-images.githubusercontent.com/96989475/148254583-ece996e0-525b-4225-8f1f-0df9854f13b1.JPG)

**Comment by Onikamitest** [comment]
Hello @jsbalasbas,

I've checked the data is all is right. Your fleed was living a bug that charge the initial values and now is updated correctly.

Thanks!
