### ISSUE TITLE
Can not get into a space station

### ISSUE THREAD

**Issue by DHodge41** [onikamigames/starshipgame#531]
I have had my account unsynced. I logged in today and the same problem is there. I can get to the space station screen, but nothing happens when I click on it. I have $800 in starship token and staked 150 wax.

My Wax account is kklyu.wam
MM account 0xBee2615EfDa21558D92D57DbDb599Ed0E225Eb71

**Comment by DHodge41** [comment]
When I try to do the Bloks.io workaround. It says error, player not found.

**Comment by Onikamitest** [comment]
Hello @DHodge41,

Could you confirm your wax account before the unsync? Thanks

**Comment by DHodge41** [comment]
My wax address is kklyu.wam.

**Comment by wangjia887** [comment]
I can't pick space station Can not get into a space station
My Wax account is khzx.wam
MM account 0xB2C6c38f872A41Bf1e3dEE3e358B6e029d59a244

**Comment by DHodge41** [comment]
My new meta mask is 0x4B9D013871C1E832C46857be4eB83De588ffdB3A
Wax is kklyu.wam

**Comment by DHodge41** [comment]
I still can not log into a space station. It says I dont have enough starship but I have 600.00
