### ISSUE TITLE
Player not Found

### ISSUE THREAD

**Issue by DHodge41** [onikamigames/starshipgame#540]
When trying to enter the space station through the bloks.io work around, it says player not found. 

My wax account is kklyu.wam. Can I be added to play the game?
MM account 0xBee2615EfDa21558D92D57DbDb599Ed0E225Eb71

**Comment by Onikamitest** [comment]
Hello @DHodge41,

I've updated your account. Seem you've setup your account with your Anchor wax account: brysongame41. But, I've checked your Metamask is not holding any balance of Starhip, so you'll find an error and need to recharge your account. Please, do it before yo sync again.

Sync and login with Wax cloud wallet to join the game. If all is right, please, close the ticket.

Thanks

**Comment by DHodge41** [comment]
I got scammed out of $800 of starship trying to login and deal with the telegram. I had to get a new MetaMask. So I just made that. I’m going to need a little to get money back. 

Will I be okay to sync a new meta mask account with that wax login?

**Comment by DHodge41** [comment]
Here is my new metamask account. 0x4B9D013871C1E832C46857be4eB83De588ffdB3A Wax account is kklyu.wam

Still can not log in

**Comment by DHodge41** [comment]
Can you please help? I still can not get into a space station. MM account
0x4B9D013871C1E832C46857be4eB83De588ffdB3A
Wax: kklyu.wam
