### ISSUE TITLE
Stuck on planet -"assertion failure with message: player has not enough starships in his/her balance","file":"cf_system.cpp" I currently have 255 SS tokens in MM

### ISSUE THREAD

**Issue by roncwarren** [onikamigames/starshipgame#545]
Hello,

I'm receiving the following error when trying to collect and return: "{"details":[{"message":"assertion failure with message: player has not enough starships in his/her balance","file":"cf_system.cpp" I currently have 255 SS tokens in MM and it was working fine last night. My Wax ID is jurj4.wam. I'm using the Binance Smart Chain in MM: https://bsc-dataseed.binance.org/

Chrome is up to date
Version 97.0.4692.71 (Official Build) (64-bit)

Thanks, Ron

**Comment by kimotsky** [comment]
Hi,

I am also receiving the same error above. I moved my StarShip token from my metamask wallet to another metamask wallet to open a new account then i bought a starship token to replace the token i took from my first account which amount to $41. I synced my metamask wallet and still receive the same error. Please need your help.

![270018867_4690471957734815_5129749987894336169_n](https://user-images.githubusercontent.com/97301066/148569305-e1eda65a-f80b-4288-9797-4e97bc399b71.png)


here's the details of my account.
Metamask wallet address: 0x25b85e82Fd90f1935B05dD75386c666252cd0C68
Wax wallet address: vllwk.wam
Browser: Chrome browser

Many thanks,

kim

**Comment by Onikamitest** [comment]
> jurj4.wam

Hello @roncwarren,

Starship balance updated, check if all is right and then close the ticket.

Thanks

**Comment by roncwarren** [comment]
This was fixed for one day and then it reverted back so I submitted another ticket.

**Comment by roncwarren** [comment]
this issue was fixed for one day and then it seems to be syncing back to my other MM account with no SS tokens. I moved all my SS tokens to my other MM account with the Ledger and this is the account that Wax is synced to.
