### ISSUE TITLE
Rarity of ships are not updating according to SS in MM

### ISSUE THREAD

**Issue by roncwarren** [onikamigames/starshipgame#550]
The rarity of my ships are not updating according to the SS in MM:

Wax: jurj4.wam
MM: 0xC958C5D9A32BD8Afc2b7052985fAe7988238Bb9D
Chrome is up to date
Version 97.0.4692.71 (Official Build) (64-bit
Ship 7827 - 7829

![Capture](https://user-images.githubusercontent.com/97129825/148638649-4974236d-57dd-4ac6-b740-adce9be6aab6.JPG)

**Comment by Onikamitest** [comment]
Data update manually, check and if all is right, close the ticket, please.
