### ISSUE TITLE
Legendry on Rare Ship Slower than Epic on Uncommon Ships ?

### ISSUE THREAD

**Issue by TopDrawerDigital** [onikamigames/starshipgame#552]
1.	MetaMask wallet address*
0x3C19DA736D96755593359c5F3cEc2004201c1e6a
2.	WAX address*
u1.uo.wam
3.	Browser & version
Chrome Version 96.0.4664.110 (Official Build) (64-bit)
4.	Exactly what you were doing when the bug occurred
Legendry Secondary Thruster on Ship 1 (Rare) is slower than other ships with Epic (UnCommon) and if I swap it for a Rare one speed increases.
5.	Screenshots/video clips (windows+alt+R to screen record)

6.	Anything you believe may be specific to your situation which may help pinpoint the issue
If I swap to a rear NFT the speed goes up and swap in back to legendary and the speed comes back down ?

**Comment by Onikamitest** [comment]
Hello @TopDrawerDigital,

We're preparing an incoming update that fix this issue. In case you still having the same issue, please, submit a new ticket.

Thanks!
