### ISSUE TITLE
I Have enough StarShip in my MetaMask but I keep getting a error when a try to do anything in game

### ISSUE THREAD

**Issue by WallaMega** [onikamigames/starshipgame#553]
Transaction was not possible.
{"details":[{"message":"assertion failure with message: player has not enought starships in his/her balance","file":"cf_system.cpp","line_number":14,"method":"eosio_assert"}],"json":{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: player has not enought starships in his/her balance","file":"cf_system.cpp","line_number":14,"method":"eosio_assert"}]}}}

Help, my info below.

0x07d1Dfc1bc1dC27524bb78cdEB50b3D196BD1355
rasyu.wam
Google Chrome

**Comment by Onikamitest** [comment]
Hello @WallaMega,

I've update your Starship balance account, check if all is right and then close the ticket.

Thanks!

**Comment by WallaMega** [comment]
Thanks, its working now.
