### ISSUE TITLE
Stuck at space station selection.

### ISSUE THREAD

**Issue by Greyvi** [onikamigames/starshipgame#554]
Metamask: 0xF92DA22eeBf7E653BD4540e5C3f488cE681220c7
Wax: jwx.2.c.wam

I already talked to Unlirice from the discord general-chat and he found out the my account show 0 starships.
I synced up before I got my SS tokens.
Unlirice said that I need to have my account resynced.
Thanks in advance.

**Comment by Onikamitest** [comment]
Hello @Greyvi,

I've updated your Starships balance account. Try to select Space Station again. If all is right, close the ticket, please.

Thanks!
