### ISSUE TITLE
Ship Rarity keeps reverting back to common ships when I have 235 SS tokens in MM.  

### ISSUE THREAD

**Issue by roncwarren** [onikamigames/starshipgame#557]
Ship Rarity keeps reverting back to common ships when I have 235 SS tokens in MM.  

Wax ID: jurj4.wam
BSC: https://bsc-dataseed.binance.org/

Chrome is up to date
Version 97.0.4692.71 (Official Build) (64-bit)
![Capture](https://user-images.githubusercontent.com/97129825/148676333-a7374889-39da-47e5-81e9-330745b3255e.JPG)

**Comment by Onikamitest** [comment]
Hi @roncwarren,

According with your Metamask address sync with your account, your actual Starship balance is 18.0146 Starships. Proof: [https://bscscan.com/token/0x52419258e3fa44deac7e670eadd4c892b480a805?a=0x7c3113115962171cd294c98e4543fbc659c7b5fc](url)

In case you'd like to upgrade your fleet, need to recharge your account again.

Thanks!

**Comment by roncwarren** [comment]
That is the wrong account. I'm synced to 0xC958C5D9A32BD8Afc2b7052985fAe7988238Bb9D

![image](https://user-images.githubusercontent.com/97129825/148762386-3ea4950a-2a46-45ff-8301-0aad1c8f71ed.png)
