### ISSUE TITLE
ships are still bugged

### ISSUE THREAD

**Issue by davinseed** [onikamigames/starshipgame#558]
I looked up my ship on starship explorer and it looks like my ship is still bugged?
wax address:
xegba.wam

![wwwaaa](https://user-images.githubusercontent.com/96920460/148688271-744278a1-d076-481c-b36a-77aafec5fc18.png)

**Comment by Onikamitest** [comment]
Hi, @davinseed 

Your fleet has been updated, please check and if all is right, close the ticket.

Thanks!

**Comment by davinseed** [comment]
wait a minute..are you guys seriously manually updating bugged ships 1 by 1? because I have a friend who also has a 2 bugged ships on his fleet. and it is unfair if his ship is still bugged while mine isn't. I think all common ships are still bugged because my friend also has a common ship same as mine.

**Comment by davinseed** [comment]
I will not close this ticket until you answer the question above

**Comment by Onikamitest** [comment]
No, the Starship update is automatically each day at 7am UTC but sometimes, based of number of petitions to the blockchain may occur some issues and the script may jump some users. Ask your friend to submit a ticket and then I could check.

Thanks!

**Comment by davinseed** [comment]
ok I will. thanks!
