### ISSUE TITLE
Starship kyanite rewards are bugged, don't get rewards for some of my completed missions on available planets. It's been inconsistent

### ISSUE THREAD

**Issue by CrypticLion** [onikamigames/starshipgame#562]
Hi, so at first it just seemed like it was my 1 starship that was bugged, the 2nd one in my inventory but now i am having multiple ships return and select another mission without being able to either claim the planet or return and collect the kyanite. Very frustrating, I lose kyanite and select another planet where it might not pay out as well. Could this be looked into? Possible bug or does this just happen sometimes? Thanks so much.
Metamask: 0x334B087EC1de6172C55AaC3A6B232ceee0b07035
WAX wallet: adtz.wam

**Comment by Onikamitest** [comment]
Hello @CrypticLion,

This is part of the game, if you're visit a planet without enough Kyanite pool the return is the max Kyanite you can mine in that available pool. We're updating the game to offer a way to know how much Kyanite the player will receive before to Collect and Return to the Space Station.

Thanks

**Comment by CrypticLion** [comment]
Oh fantastic, thanks for the reply!
