### ISSUE TITLE
Need to Manual Unsync My Account. Wrong Sync.

### ISSUE THREAD

**Issue by wakanestar** [onikamigames/starshipgame#563]
Hi good day Dev,

Hi Please Help me to manual unsync my account:

My WAX WALLET ADD: 4xkkw.c.wam
My METAMASK ADD: 0xDD0261Ad92CC9335D6b233d5481928E816e1Ec75

![viber_image_2022-01-11_10-32-18-173](https://user-images.githubusercontent.com/97490923/148871070-0780b45d-422e-40a6-848f-bbb11b683f64.jpg)

**Comment by Onikamitest** [comment]
Hello @wakanestar,

The only way to unsync your account is deleting it. But I can see you're staking 455.29 Kyanite. Update the ticket when you've unstake the Kyanite running this action: https://wax.bloks.io/account/starshipgame?loadContract=true&tab=Actions&account=starshipgame&scope=starshipgame&limit=100&action=withdraw

Thanks

**Comment by wakanestar** [comment]
Hi i already solved my issue. in already transfer my SS token to a new metamask.
