### ISSUE TITLE
cant lunch my ship the lunch button covered.

### ISSUE THREAD

**Issue by Aerogaming92** [onikamigames/starshipgame#564]
i cant lunch my ship because the detailed of the planet is covering the lunch button and i cant even see the rewards pool of that planet i hope you can fix this problem as soon as possible so i can mine kyanite everyday.

wax wallet: zd1xg.wam
metamask: 0xa98269acDeD5235b6dDB1a647FF074504b1BCdDc

**Comment by Onikamitest** [comment]
Hello @Aerogaming92,

This issue is solved.

Thanks
