### ISSUE TITLE
Ship rarity not sync

### ISSUE THREAD

**Issue by kim5266** [onikamigames/starshipgame#566]
Good day,

I added starship tokens on my metamask a week ago and reached the 100 dollar threshold to get rare ships. I already reached out to tg and discord but no one helps me. Until now my ships are common. Please help.

Metamask: 0x407b1bA9D81b27769419c131ce9bb5BaB2763646

Wax: unvxk.wam

thanks

**Comment by kim5266** [comment]
I am holding 142 tokens please see screenshot. 
![IMG_20220111_162701](https://user-images.githubusercontent.com/97508884/148907137-6e8099f0-664a-47b2-b419-bd1734b43475.jpg)

**Comment by Onikamitest** [comment]
Hello, @kim5266, your balance has been updated. Please, if all is right, close the ticket.

**Comment by kim5266** [comment]
Hi, my ships rarity is not updating for two days now even though it reaches rare 100$ above. Please check

Metamask: 0x407b1bA9D81b27769419c131ce9bb5BaB2763646

Wax: unvxk.wam

![IMG_20220116_014932](https://user-images.githubusercontent.com/97508884/149632305-17379126-a95b-47fb-ad38-ee4f7fede4a9.jpg)

Thanks.
